#!/bin/bash
#
# Name: ragnar
# Auth: Gavin Lloyd <gavinhungry@gmail.com>
# Desc: Mount an existing remote LUKS device with NBD over SSH
#
# Released under the terms of the MIT license
# https://github.com/gavinhungry/ragnar
#

[ ${_ABASH:-0} -ne 0 ] || source $(dirname "${BASH_SOURCE}")/abash/abash.sh

SERVER=${RAGNAR_SERVER:-localhost}
EXPORT=${RAGNAR_EXPORT:-${RAGNAR_NBDEXPORT:-ragnar}} # legacy RAGNAR_NBDEXPORT
PORT=${RAGNAR_PORT:-10809}
HEADER=${RAGNAR_HEADER:-/etc/luks/${EXPORT}.header}
KEYFILE=${RAGNAR_KEYFILE:-/etc/luks/${EXPORT}.key}
MOUNTPOINT=${RAGNAR_MOUNTPOINT:-}
MOUNT_OPTIONS=${RAGNAR_MOUNT_OPTIONS:-}

TMP=$(tmpdirp "${SERVER}-${EXPORT}")
mkdir -p ${TMP}

ssh_is_open() {
  ssh -qO check -S "${TMP}/ssh" ${SERVER} &> /dev/null
}

open_ssh() {
  ssh -fNn -MS "${TMP}/ssh" -L ${PORT}:127.0.0.1:10809 ${SERVER}
}

close_ssh() {
  if ssh_is_open; then
    ssh -qO exit -S "${TMP}/ssh" ${SERVER}
  fi
}

nbd_device() {
  cat "${TMP}/nbd" 2> /dev/null
}

nbd_is_open() {
  [ -f "/sys/block/${1}/pid" ]
}

nbd_next_open() {
  checksu modprobe nbd

  for DEV in /dev/nbd*; do
    NBD=$(echo ${DEV} | cut -d'/' -f3)
    if ! nbd_is_open ${NBD}; then
      echo ${NBD}
      return
    fi
  done
}

export_is_open() {
  [ -f "${TMP}/nbd" ] || return 1
  nbd_is_open $(nbd_device)
}

open_export() {
  checksu modprobe nbd
  NBD=$1

  if quietly checksu nbd-client 127.0.0.1 ${PORT} /dev/${NBD} -name ${EXPORT}; then
    echo ${NBD} > ${TMP}/nbd
  else
    close_ssh
    rm -fr ${TMP}
    return 1
  fi
}

close_export() {
  if export_is_open; then
    checksu
    checksu modprobe nbd
    quietly checksu nbd-client -d /dev/$(nbd_device) && quietly rm -f "${TMP}/nbd"
  fi
}

luks_is_open() {
  [ -b /dev/mapper/${EXPORT} ]
}

luks_open() {
  NBD=$1
  checksu [ -f "${HEADER}" ] || HEADER="${NBD}"
  checksu cryptsetup luksOpen /dev/${NBD} ${EXPORT} -d "${KEYFILE}" --header "${HEADER}"
}

luks_close() {
  checksu cryptsetup luksClose /dev/mapper/${EXPORT}
}

filesystem_mountpoint() {
  udisksctl info -b /dev/mapper/${EXPORT} 2> /dev/null | grep MountPoints | cut -d':' -f2 | sed 's/^\s*//'
}

filesystem_is_mounted() {
  [ -n "$(filesystem_mountpoint)" ]
}

mount_filesystem() {
  local -a COMMAND

  if [ -n "${MOUNTPOINT}" ]; then
    COMMAND=(mount)
  else
    COMMAND=(udisksctl mount -b /dev/mapper/${EXPORT})
  fi

  [ -z "${MOUNT_OPTIONS}" ] || COMMAND+=(-o "${MOUNT_OPTIONS}")
  [ -z "${MOUNTPOINT}" ] || COMMAND+=(/dev/mapper/${EXPORT} "${MOUNTPOINT}")

  quietly checksu "${COMMAND[@]}"
}

unmount_filesystem() {
  if [ -n "${MOUNTPOINT}" ]; then
    quietly checksu umount "${MOUNTPOINT}"
  else
    quietly checksu udisksctl unmount -b /dev/mapper/${EXPORT}
  fi
}

open_transport() {
  export_is_open && die "${EXPORT} already open on $(nbd_device)"

  inform "Opening SSH connection to ${SERVER}"
  open_ssh || die "Could not open SSH connection to ${SERVER}"
  sleep 1

  NBD=$(nbd_next_open)
  inform "Opening network block device on /dev/${NBD}"
  open_export ${NBD} || die "Could not open network block device on /dev/${NBD}"
}

close_transport() {
  FAILED=0
  NBD=$(nbd_device)

  if export_is_open; then
    inform "Closing network block device on /dev/${NBD}"
    close_export || FAILED=1
  fi

  if ssh_is_open; then
    inform "Closing SSH connection to ${SERVER}"
    close_ssh || FAILED=1
  fi

  [ ${FAILED} -eq 0 ] || return 1
  tmpdirclean
}

attach() {
  open_transport >&2 || return 1
  echo "/dev/${NBD}"
}

detach() {
  close_transport >&2
}

open() {
  export_is_open && die "${EXPORT} already open on $(nbd_device)"
  checksu [ -f "${KEYFILE}" ] || die "Keyfile not found"
  [ -z "${MOUNTPOINT}" ] || [ -d "${MOUNTPOINT}" ] || die "Mountpoint does not exist: ${MOUNTPOINT}"

  open_transport

  inform "Opening LUKS device from /dev/${NBD}"
  luks_open ${NBD} || die "Could not open LUKS device from /dev/${NBD}"

  inform "Mounting filesystem from /dev/mapper/${EXPORT}"
  mount_filesystem || die "Could not mount filesystem from /dev/mapper/${EXPORT}"

  msg "Filesystem is mounted on $(filesystem_mountpoint)"
}

close() {
  export_is_open || die "${EXPORT} is not open"
  NBD=$(nbd_device)

  checksu

  MOUNTPOINT=$(filesystem_mountpoint)

  filesystem_is_mounted && inform "Closing filesystem on ${MOUNTPOINT}"
  unmount_filesystem || die "Could not close filesystem on ${MOUNTPOINT}"

  luks_is_open && inform "Closing LUKS device from /dev/${NBD}"
  luks_close || die "Could not close LUKS device from /dev/${NBD}"

  close_transport
}

case $1 in
  'open') open ;;
  'close') close ;;
  'attach') attach ;;
  'detach') detach ;;
  *) usage '[open|close|attach|detach]' ;;
esac
